version: "3"
services:
  jupyter:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - USER_ID=${USER_ID} #* 
        - GROUP_ID=${GROUP_ID} #* 
        - USER=${USER_NAME} #*
    ports:
      - "${JUPYTER_PORT}:8888" #*
    expose:
      - "8888"
    environment:
      - WANDB_API_KEY=${WANDB_API_KEY} #*
    volumes:
      - ./:/home/${USER_NAME}/work #*
      - ${LOCAL_DATA_PATH}:/home/${USER_NAME}/data/ #*
