name: python-gpu-env

channels:
  - defaults
  - conda-forge
  - fastai

dependencies:
  - cudatoolkit=11.2
  - fastgpu
  - git
  - gh
  - ipywidgets
  - jupyterlab
  - jupyterlab-git
  - keyrings.alt
  - matplotlib
  - nano
  - nbclassic>=0.2.8
  - nbdev
  - nodejs
  - numpy
  - pip==20.2
  - pip:
     - jupyterlab-quickopen
     - aquirdturtle_collapsible_headings
  - python=3.8
  - seaborn
  - twine
  - xeus-python
  - wandb
