version: "3.7"

services:
  jupyterlab-server:
    build:
      args:
        - username=${USER_NAME}
        - uid=${USER_ID}
        - gid=${GROUP_ID}
      context: ../
      dockerfile: Dockerfile-conda
    ports:
      - "${JUPYTER_PORT}:8888"
    runtime: nvidia
    volumes:
      - ./:/home/${USER}/work
    init: true
    stdin_open: true
    tty: true    
