name: python-gpu-env

channels:
  - defaults
  - conda-forge
  - fastai

dependencies:
  - fastgpu
  - git
  - gh
  - ipywidgets
  - jupyterlab
  - jupyterlab-git
  - jupyterlab-lsp
  - keyrings.alt
  - matplotlib
  - nbclassic>=0.2.8
  - nbdev
  - nodejs
  - numpy
  - pip==20.2
  - pip:
     - jupyterlab-quickopen
     - aquirdturtle_collapsible_headings
     - git+https://github.com/krassowski/python-language-server.git@main
   #  - git+https://github.com/timeseriesAI/tsai.git
   # - -r file:/tmp/requirements.txt	
  - python=3.8
  #- python-language-server
  - twine
  - xeus-python
  - wandb
